version: "3.7"

services:
  gofindpi:
    image: gofindpi:1.0
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
    - mynet
    # rest of service config and other services removed for clarity

networks:
  mynet:
    name: mynet
    ipam:
      driver: default
      config:
      - subnet: "192.168.32.0/20"

